const SAFE_EVENT_ID_MAX_LENGTH = 200;

export function sseEventId(data) {
  try {
    const id = JSON.parse(String(data))?._sseId;
    if (typeof id !== "string" || !id || id.length > SAFE_EVENT_ID_MAX_LENGTH || /[\0\r\n]/.test(id)) return null;
    return id;
  } catch {
    return null;
  }
}

/** Format one SSE message, optionally exposing its durable ID to EventSource. */
export function sseDataFrame(data, { includeId = true } = {}) {
  const value = String(data);
  const id = includeId ? sseEventId(value) : null;
  const payload = value.split(/\r?\n/).map((line) => `data: ${line}`).join("\n");
  return `${id ? `id: ${id}\n` : ""}${payload}\n\n`;
}

/** Accept only the bounded, single-line IDs generated by Oyster. */
export function normalizeLastEventId(value) {
  const candidate = Array.isArray(value) ? value[0] : value;
  if (typeof candidate !== "string" || !candidate || candidate.length > SAFE_EVENT_ID_MAX_LENGTH || /[\0\r\n]/.test(candidate)) return null;
  return candidate;
}
